site_name: Useful Websites
theme:
  features:
    - navigation.instant
    - navigation.tabs
  name: material
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - scheme: slate
    primary: deep purple
    accent: deep purple
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

nav:
  - Home: index.md
  - Nintendo Switch: nx.md
  - PC: pc.md
  - Piracy: piracy.md
  - Emulation: emulation.md
  - Hacking Guides: hackingguides.md
  - 'Setting up a Minecraft server':
    - The Computer: minecraftserver/computer.md
    - Setting up the Server Software: minecraftserver/setupserver.md
    - Server Management: minecraftserver/management.md
    - Useful links and extras: minecraftserver/extras.md
