site_name: Useful Websites
theme: material
nav:
  - Home: index.md
  - Nintendo Switch: nx.md
  - PC: pc.md
  - Piracy: piracy.md
  - Emulation: emulation.md
  - Hacking Guides: hackingguides.md
  - Setting up a Minecraft server: minecraftserver.md