site_name: Useful Websites
theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - scheme: slate
    primary: red
    accent: red
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

nav:
  - Home: index.md
  - Nintendo Switch: nx.md
  - PC: pc.md
  - Piracy: piracy.md
  - Emulation: emulation.md
  - Hacking Guides: hackingguides.md
  - Setting up a Minecraft server: minecraftserver.md
